### ISSUE TITLE
build error !

### ISSUE THREAD

**Issue by XxxA90xxX** [proferabg/ReClass.NET-Xbox360#1]
just try to build with visual studio 2019 and i got more than 80 errors and i think this is not for windows 64 
i hope you can fix it or build it and re-upload it again.

**Comment by proferabg** [comment]
It does compile with VS2019 and VS2022. Did you follow the compile instructions? Also a bit more information would help me to figure out why you are getting errors.

**Comment by proferabg** [comment]
You didn't follow the compile instructions in the README and you are missing references to xdevkit and JRPC

**Comment by proferabg** [comment]
> Just fork and clone and after that what i must do? what folder i must create and where? 
You obviously did not read the README for setting up the ReClass.Net project and folder structure. The release files are posted with instructions to follow.
